#!/bin/sh

mkdir -p src/thirdparty &&
cd src/thirdparty &&

# image reading
# curl https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -o stb_image.h -s &&
curl https://raw.githubusercontent.com/jackodirks/stb/master/stb_image.h -o stb_image.h -s && # fork with an annoying gcc warning fix
# https://github.com/nothings/stb/pull/1016

echo deps downloaded
