#!/bin/sh
./getdeps
rm build -rf &&
echo ========================== compiling the code =========================== &&
mkdir -p ./build &&
cd build &&
cmake ../ &&
make &&
echo ========================== running the code ============================= &&
./rendering &&
cd ..
