#!/bin/sh
rm build -rf &&
echo ========================== compiling the code =========================== &&
mkdir -p ./build/out/ &&
cd build &&
cmake .. -DCMAKE_BUILD_TYPE=Debug &&
make &&
echo ========================== running the code =============================
./rendering &
sleep 0.5
i3-msg "floating toggle"
cd ..
