#!/bin/sh
gcc main.c camera.c vectormath.c render.c shapes.c color.c -obuild -pthread -lm && ./build
: '
ffmpeg -r 20 -s 600x600 -i %04d.bmp anim.mp4
gcc main.c vectormath.c render.c -pthread -lm -ggdb
gdb a.out
'
