/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_H_
# define FRAG_H_

const char *fragFull_glsl =
 "#version 330 core\n"
 "out vec4 outColor;"
 "float f(in vec2 i)"
 "{"
   "return dot(i,i);"
 "}"
 "float i(in vec3 i)"
 "{"
   "return dot(i,i);"
 "}"
 "float f(in vec2 v,in vec2 i)"
 "{"
   "return v.x*i.x-v.y*i.y;"
 "}"
 "float f(in vec3 i,in vec3 v,in float y)"
 "{"
   "return length(i-v)-y;"
 "}"
 "float f(in vec3 v,in vec3 i,in vec3 y,in float z)"
 "{"
   "vec3 r=v-i,m=abs(r)-y;"
   "return length(max(m,0.))+min(max(m.x,max(m.y,m.z)),0.)-z;"
 "}"
 "float i(vec3 v,vec3 i,vec3 y,float z)"
 "{"
   "vec3 r=v-i;"
   "r=abs(r)-y;"
   "vec3 m=abs(r+z)-z;"
   "return min(min(length(max(vec3(r.x,m.y,m.z),0.))+min(max(r.x,max(m.y,m.z)),0.),length(max(vec3(m.x,r.y,m.z),0.))+min(max(m.x,max(r.y,m.z)),0.)),length(max(vec3(m.x,m.y,r.z),0.))+min(max(m.x,max(m.y,r.z)),0.));"
 "}"
 "float i(vec3 v,vec3 i,vec2 y)"
 "{"
   "vec3 m=v-i;"
   "vec2 r=vec2(length(m.xz)-y.x,m.y);"
   "return length(r)-y.y;"
 "}"
 "float f(in vec3 v,in vec3 i,in vec2 m,in float d,in float y)"
 "{"
   "vec3 r=v-i;"
   "r.x=abs(r.x);"
   "float z=m.y*r.x>m.x*r.y?dot(r.xy,m):length(r.xy);"
   "return sqrt(dot(r,r)+d*d-2.*d*z)-y;"
 "}"
 "float i(vec3 v,vec3 i,float y,float r,float z)"
 "{"
   "vec3 m=v-i,d=vec3(m.x,max(abs(m.y)-y,0.),m.z);"
   "return length(vec2(length(d.xy)-r,d.z))-z;"
 "}"
 "float v(vec3 v,vec3 i,vec3 r,float y)"
 "{"
   "vec3 m=v-i;"
   "return dot(m,normalize(r))+y;"
 "}"
 "float v(vec3 v,vec3 i,vec2 r)"
 "{"
   "vec3 m=v-i;"
   "const vec3 d=vec3(-.866025,.5,.57735);"
   "m=abs(m);"
   "m.xy-=2.*min(dot(d.xy,m.xy),0.)*d.xy;"
   "vec2 f=vec2(length(m.xy-vec2(clamp(m.x,-d.z*r.x,d.z*r.x),r.x))*sign(m.y-r.x),m.z-r.y);"
   "return min(max(f.x,f.y),0.)+length(max(f,0.));"
 "}"
 "float t(vec3 v,vec3 i,vec2 r)"
 "{"
   "vec3 m=v-i,d=abs(m);"
   "return max(d.z-r.y,max(d.x*.866025+m.y*.5,-m.y)-r.x*.5);"
 "}"
 "float t(vec3 v,vec3 i,vec3 y,float r)"
 "{"
   "vec3 m=v-i,d=y-i;"
   "float z=clamp(dot(m,d)/dot(d,d),0.,1.);"
   "return length(m-d*z)-r;"
 "}"
 "float n(in vec3 v,in vec3 i,in vec3 y,in float d)"
 "{"
   "vec3 r=y-i,m=v-i;"
   "float z=dot(r,r),f=dot(m,r),c=length(m*z-r*f)-d*z,a=abs(f-z*.5)-z*.5,x=c*c,o=a*a*z,l=max(c,a)<0.?-min(x,o):(c>0.?x:0.)+(a>0.?o:0.);"
   "return sign(l)*sqrt(abs(l))/z;"
 "}"
 "float n(vec3 i,vec3 v,vec3 m,float y,float r)"
 "{"
   "float d=r-y,z=dot(m-v,m-v),f=dot(i-v,i-v),c=dot(i-v,m-v)/z,a=sqrt(f-c*c*z),l=max(0.,a-(c<.5?y:r)),o=abs(c-.5)-.5,x=d*d+z,g=clamp((d*(a-y)+c*z)/x,0.,1.),b=a-y-g*d,s=c-g,p=b<0.&&o<0.?-1.:1.;"
   "return p*sqrt(min(l*l+o*o*z,b*b+s*s*z));"
 "}"
 "float n(vec3 v,vec3 i,float d)"
 "{"
   "vec3 m=v-i;"
   "float r=d*d+.25;"
   "m.xz=abs(m.xz);"
   "m.xz=m.z>m.x?m.zx:m.xz;"
   "m.xz-=.5;"
   "vec3 c=vec3(m.z,d*m.y-.5*m.x,d*m.x+.5*m.y);"
   "float z=max(-c.x,0.),y=clamp((c.y-.5*m.z)/(r+.25),0.,1.),f=r*(c.x+z)*(c.x+z)+c.y*c.y,o=r*(c.x+.5*y)*(c.x+.5*y)+(c.y-r*y)*(c.y-r*y),l=min(c.y,-c.x*r-c.y*.5)>0.?0.:min(f,o);"
   "return sqrt((l+c.z*c.z)/r)*sign(max(c.z,-m.y));"
 "}"
 "float x(vec3 v,vec3 y,vec3 r,vec3 z)"
 "{"
   "vec3 d=r-y,m=v-y,c=z-r,f=v-r,x=y-z,o=v-z,l=cross(d,x);"
   "return sqrt(sign(dot(cross(d,l),m))+sign(dot(cross(c,l),f))+sign(dot(cross(x,l),o))<2.?min(min(i(d*clamp(dot(d,m)/i(d),0.,1.)-m),i(c*clamp(dot(c,f)/i(c),0.,1.)-f)),i(x*clamp(dot(x,o)/i(x),0.,1.)-o)):dot(l,m)*dot(l,m)/i(l));"
 "}"
 "float t(vec3 v,vec3 y,vec3 r,vec3 m,vec3 z)"
 "{"
   "vec3 d=r-y,f=v-y,c=m-r,o=v-r,x=z-m,l=v-m,g=y-z,p=v-z,a=cross(d,g);"
   "return sqrt(sign(dot(cross(d,a),f))+sign(dot(cross(c,a),o))+sign(dot(cross(x,a),l))+sign(dot(cross(g,a),p))<3.?min(min(min(i(d*clamp(dot(d,f)/i(d),0.,1.)-f),i(c*clamp(dot(c,o)/i(c),0.,1.)-o)),i(x*clamp(dot(x,l)/i(x),0.,1.)-l)),i(g*clamp(dot(g,p)/i(g),0.,1.)-p)):dot(a,f)*dot(a,f)/i(a));"
 "}"
 "float x(float i,float v,float y)"
 "{"
   "float r=clamp(.5+.5*(v-i)/y,0.,1.);"
   "return mix(v,i,r)-y*r*(1.-r);"
 "}"
 "float s(float i,float v,float y)"
 "{"
   "float r=clamp(.5-.5*(v+i)/y,0.,1.);"
   "return mix(v,-i,r)+y*r*(1.-r);"
 "}"
 "float h(float i,float v,float y)"
 "{"
   "float r=clamp(.5-.5*(v-i)/y,0.,1.);"
   "return mix(v,i,r)+y*r*(1.-r);"
 "}"
 "const int r=1024;"
 "const float y=.0001,z=30.;"
 "const int m=0,c=15,d=c*2+4,w=3;"
 "uniform float time;"
 "uniform vec3 lightPos;"
 "uniform ivec2 resolution;"
 "uniform vec3 cam[5];"
 "uniform float rawGroups[w*d];"
 "vec4 e[w*d];"
 "int h(int v)"
 "{"
   "return int(rawGroups[d*v+c*2+0]);"
 "}"
 "int n(int v)"
 "{"
   "return int(rawGroups[d*v+c*2+1]);"
 "}"
 "int s(int v)"
 "{"
   "return int(rawGroups[d*v+c*0+1]);"
 "}"
 "int t(int v)"
 "{"
   "return int(rawGroups[d*v+c*1+1]);"
 "}"
 "int v(int v)"
 "{"
   "return int(rawGroups[d*v+c*2+2]);"
 "}"
 "float x(int v)"
 "{"
   "return rawGroups[d*v+c*2+3];"
 "}"
 "float p(int v)"
 "{"
   "return rawGroups[d*v+c*0+9];"
 "}"
 "float l(int v)"
 "{"
   "return rawGroups[d*v+c*1+9];"
 "}"
 "vec3 o(int v)"
 "{"
   "return vec3(rawGroups[d*v+0],rawGroups[d*v+1],rawGroups[d*v+2]);"
 "}"
 "vec3 a(int v)"
 "{"
   "return vec3(rawGroups[d*v+3],rawGroups[d*v+4],rawGroups[d*v+5]);"
 "}"
 "vec3 u(int v)"
 "{"
   "return vec3(rawGroups[d*v+6],rawGroups[d*v+7],rawGroups[d*v+8]);"
 "}"
 "vec2 G(int v)"
 "{"
   "return vec2(rawGroups[d*v+9],rawGroups[d*v+10]);"
 "}"
 "float G(int v,int i)"
 "{"
   "return rawGroups[d*v+i];"
 "}"
 "vec3 g(int v)"
 "{"
   "return vec3(rawGroups[d*v+0+c],rawGroups[d*v+1+c],rawGroups[d*v+2+c]);"
 "}"
 "vec3 b(int v)"
 "{"
   "return vec3(rawGroups[d*v+3+c],rawGroups[d*v+4+c],rawGroups[d*v+5+c]);"
 "}"
 "vec3 C(int v)"
 "{"
   "return vec3(rawGroups[d*v+6+c],rawGroups[d*v+7+c],rawGroups[d*v+8+c]);"
 "}"
 "vec2 q(int v)"
 "{"
   "return vec2(rawGroups[d*v+9+c],rawGroups[d*v+10+c]);"
 "}"
 "float C(int v,int i)"
 "{"
   "return rawGroups[d*v+i+c];"
 "}struct rayHit{vec3 hitPos;vec3 surfaceClr;int steps;bool hit;};"
 "vec4 C(in float v,in float i,in vec3 r,in vec3 m,in float y)"
 "{"
   "float d=clamp(.5+.5*(i-v)/y,0.,1.),f=mix(i,v,d)-y*d*(1.-d);"
   "vec3 c=mix(m,r,d);"
   "return vec4(c,f);"
 "}"
 "vec4 G(in float v,in float i,in vec3 d,in vec3 y,in float r)"
 "{"
   "float m=1.-r,f=v*m+i*r;"
   "vec3 c=d*m+y*r;"
   "return vec4(c,f);"
 "}"
 "vec4 C(in float v,in float i,in vec3 r,in vec3 m,in int d,in float f)"
 "{"
   "float y=v;"
   "vec3 c=r;"
   "if(d==1)"
     "{"
       "vec4 a=C(v,i,r,m,f);"
       "y=a.w;"
       "c=a.xyz;"
     "}"
   "else"
     " if(d==4)"
       "{"
         "vec4 a=G(v,i,r,m,f);"
         "y=a.w;"
         "c=a.xyz;"
       "}"
     "else"
       " if(d==0)"
         "{"
           "if(i<v)"
             "y=i,c=m;"
         "}"
       "else"
         " if(d==2)"
           "{"
             "if(-i>y)"
               "y=-i,c=m;"
           "}"
         "else"
           " if(d==3)"
             "{"
               "if(i>y)"
                 "y=i,c=m;"
             "}"
   "return vec4(c,y);"
 "}"
 "vec3 P(in vec3 v)"
 "{"
   "v+=vec3(4.);"
   "if((int(v.x)+int(v.y)+int(v.z))%2==0.)"
     "return vec3(.5);"
   "else"
     " return vec3(.7);"
 "}"
 "void P(in vec3 m,in int d)"
 "{"
   "float r,y;"
   "vec3 c,z;"
   "if(h(d)==0)"
     "{"
       "vec4 H=e[s(d)];"
       "r=H.w;"
       "c=H.xyz;"
     "}"
   "else"
     " if(h(d)==1)"
       "c=a(d),r=f(m,o(d),u(d),p(d));"
     "else"
       " if(h(d)==2)"
         "c=a(d),r=f(m,o(d),p(d));"
       "else"
         " if(h(d)==3)"
           "c=a(d),r=n(m,o(d),u(d),p(d));"
         "else"
           " if(h(d)==4)"
             "c=a(d),r=i(m,o(d),u(d),p(d));"
           "else"
             " if(h(d)==5)"
               "c=a(d),r=i(m,o(d),G(d));"
             "else"
               " if(h(d)==6)"
                 "c=a(d),r=f(m,o(d),G(d),G(d,11),G(d,12));"
               "else"
                 " if(h(d)==7)"
                   "c=a(d),r=i(m,o(d),G(d,11),G(d,9),G(d,10));"
                 "else"
                   " if(h(d)==8)"
                     "c=a(d),r=v(m,o(d),u(d),p(d));"
                   "else"
                     " if(h(d)==9)"
                       "c=a(d),r=v(m,o(d),G(d));"
                     "else"
                       " if(h(d)==10)"
                         "c=a(d),r=t(m,o(d),G(d));"
                       "else"
                         " if(h(d)==11)"
                           "c=a(d),r=t(m,o(d),u(d),p(d));"
                         "else"
                           " if(h(d)==12)"
                             "c=a(d),r=n(m,o(d),u(d),G(d,9),G(d,10));"
                           "else"
                             " if(h(d)==13)"
                               "c=a(d),r=n(m,o(d),p(d));"
   "if(n(d)==0)"
     "{"
       "vec4 H=e[t(d)];"
       "y=H.w;"
       "z=H.xyz;"
     "}"
   "else"
     " if(n(d)==1)"
       "z=b(d),y=f(m,g(d),C(d),l(d));"
     "else"
       " if(n(d)==2)"
         "z=b(d),y=f(m,g(d),l(d));"
       "else"
         " if(n(d)==3)"
           "z=b(d),y=n(m,g(d),C(d),l(d));"
         "else"
           " if(n(d)==4)"
             "z=b(d),y=i(m,g(d),C(d),l(d));"
           "else"
             " if(n(d)==5)"
               "z=b(d),y=i(m,g(d),q(d));"
             "else"
               " if(n(d)==6)"
                 "z=b(d),y=f(m,g(d),q(d),C(d,11),C(d,12));"
               "else"
                 " if(n(d)==7)"
                   "z=b(d),y=i(m,g(d),C(d,11),C(d,9),C(d,10));"
                 "else"
                   " if(n(d)==8)"
                     "z=b(d),y=v(m,g(d),C(d),l(d));"
                   "else"
                     " if(n(d)==9)"
                       "z=b(d),y=v(m,g(d),q(d));"
                     "else"
                       " if(n(d)==10)"
                         "z=b(d),y=t(m,g(d),q(d));"
                       "else"
                         " if(n(d)==11)"
                           "z=b(d),y=t(m,g(d),C(d),l(d));"
                         "else"
                           " if(n(d)==12)"
                             "z=b(d),y=n(m,g(d),C(d),C(d,9),C(d,10));"
                           "else"
                             " if(n(d)==13)"
                               "z=b(d),y=n(m,g(d),l(d));"
   "e[d]=C(r,y,c,z,v(d),x(d));"
 "}"
 "vec4 H(in vec3 d)"
 "{"
   "float v=200.;"
   "vec3 i=vec3(0.);"
   "for(int r=0;r<w;r++)"
     "P(d,r);"
   "i=e[w-1].xyz;"
   "v=e[w-1].w;"
   "float r=f(d,vec3(0.,-1.,0.),vec3(4.,2.,4.),0.);"
   "vec4 m=C(v,r,i,P(d),0,0.);"
   "i=m.xyz;"
   "v=m.w;"
   "return vec4(i,v);"
 "}"
 "vec3 F(in vec3 d)"
 "{"
   "const vec3 v=vec3(.001,0.,0.);"
   "float i=H(d+v.xyy).w-H(d-v.xyy).w,r=H(d+v.yxy).w-H(d-v.yxy).w,y=H(d+v.yyx).w-H(d-v.yyx).w;"
   "return normalize(vec3(i,r,y));"
 "}"
 "rayHit F(in vec3 v,in vec3 d)"
 "{"
   "float i=0.;"
   "for(int m=0;m<r;++m)"
     "{"
       "vec3 c=v+i*d;"
       "vec4 a=H(c);"
       "float f=a.w;"
       "if(f<y)"
         "{"
           "vec3 o=a.xyz,x=F(c),l=normalize(lightPos-c);"
           "float s=max(0.,dot(x,l))*.9;"
           "return rayHit(c,o*s,m,true);"
         "}"
       "i+=f;"
       "if(f>z)"
         "return rayHit(vec3(0.),vec3(.1),m,false);"
     "}"
   "return rayHit(vec3(0.),vec3(.1),r,false);"
 "}"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/resolution.xy;"
   "if((int(gl_FragCoord.x)+int(gl_FragCoord.y))%(m+1)!=0)"
     "{"
       "outColor=vec4(0.);"
       "return;"
     "}"
   "vec3 i=mix(cam[4],cam[2],v.y),d=mix(cam[3],cam[1],v.y),r=mix(d,i,v.x),f=normalize(r-cam[0]),c;"
   "rayHit a=F(cam[0],f);"
   "c=a.surfaceClr;"
   "vec3 z=F(a.hitPos)*y*10,o=a.hitPos+z,l=normalize(lightPos-o);"
   "outColor=vec4(c,1.);"
 "}";

#endif // FRAG_H_
